# Generated by Django 6.0.6 on 2026-09-04 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('issue_date', models.CharField(max_length=100)),
                ('credential_id', models.CharField(blank=True, default='', max_length=150)),
                ('verification_url', models.URLField(blank=True, default='')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certifications/')),
                ('certificate_image_url', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(blank=True, default='', max_length=200)),
                ('start_year', models.CharField(max_length=50)),
                ('end_year', models.CharField(blank=True, default='Present', max_length=50)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('employment_type', models.CharField(blank=True, default='Full-time', max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(blank=True, default='Present', max_length=100)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='experience/')),
                ('company_logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media_library/%Y/%m/')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('file_type', models.CharField(blank=True, default='image', max_length=50)),
                ('file_size', models.IntegerField(default=0, help_text='Size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Alex Morgan', max_length=150)),
                ('title', models.CharField(default='UI/UX Designer & Frontend Developer', max_length=200)),
                ('bio', models.TextField(default='I design and build beautiful, intuitive, and accessible digital products.')),
                ('hero_headline', models.CharField(default='Crafting exceptional digital experiences through code & design.', max_length=250)),
                ('hero_subheading', models.CharField(default='Specializing in modern web applications, design systems, and seamless user interfaces.', max_length=300)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('resume_url', models.CharField(blank=True, default='', max_length=500)),
                ('email', models.EmailField(default='alex.morgan@example.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+1 (555) 234-5678', max_length=50)),
                ('location', models.CharField(default='San Francisco, CA', max_length=150)),
                ('github_url', models.URLField(blank=True, default='https://github.com')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com')),
                ('figma_url', models.URLField(blank=True, default='https://figma.com')),
                ('dribbble_url', models.URLField(blank=True, default='https://dribbble.com')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(default='UI/UX Design', max_length=100)),
                ('short_description', models.TextField()),
                ('full_case_study', models.JSONField(blank=True, default=list, help_text='Structured array of case study sections')),
                ('technologies', models.JSONField(blank=True, default=list, help_text='Array of tech stack strings')),
                ('project_date', models.CharField(blank=True, default='2025', max_length=100)),
                ('live_url', models.URLField(blank=True, default='')),
                ('github_url', models.URLField(blank=True, default='')),
                ('figma_url', models.URLField(blank=True, default='')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/')),
                ('thumbnail_url', models.CharField(blank=True, default='', max_length=500)),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='List of media URLs')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('UI/UX Design', 'UI/UX Design'), ('Frontend Development', 'Frontend Development'), ('Tools & Softwares', 'Tools & Softwares'), ('Methodologies', 'Methodologies')], default='UI/UX Design', max_length=100)),
                ('icon', models.CharField(blank=True, default='Code', help_text='Lucide icon name or URL', max_length=100)),
                ('level', models.IntegerField(default=85, help_text='Skill percentage 0-100')),
                ('level_label', models.CharField(blank=True, default='Advanced', max_length=50)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
