# Generated by Django 6.0.6 on 2026-09-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='I design and build modern, intuitive, and accessible web applications.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dribbble_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='sivakumarpetla9@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='figma_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='Petla Siva Kumar', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.URLField(blank=True, default='https://github.com/sivakumarpetla9-cpu'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hero_headline',
            field=models.CharField(default='Designing intuitive interfaces. Engineering performant web apps.', max_length=250),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hero_subheading',
            field=models.CharField(default='Specializing in end-to-end product design, scalable frontend architecture, and interactive design systems.', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://www.linkedin.com/in/siva-kumar-33b206377/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='India', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default='UI/UX Designer & Frontend Developer (Fresher)', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
