# Generated by Django 6.0.6 on 2026-09-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_bio_alter_profile_dribbble_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='work_mode',
            field=models.CharField(choices=[('Remote', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], default='Remote', max_length=20),
        ),
    ]
