# Generated by Django 6.0.6 on 2026-09-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_experience_work_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='work_mode',
            field=models.CharField(choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], default='Remote', max_length=20),
        ),
    ]
